package scaffold

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"testing"

	"github.com/TheBud4/ray/internal/profile"
	"github.com/TheBud4/ray/internal/runner"
	"github.com/TheBud4/ray/internal/store"
)

var wantBasePaths = []string{
	"CLAUDE.md",
	"SECURITY.md",
	"docs/README.md",
	"docs/architecture.md",
	"docs/conventions.md",
	".claude/commands/document.md",
	".claude/commands/handoff.md",
	".claude/commands/revisar.md",
	".claude/commands/destilar.md",
	".claude/handoff.md",
}

func baseFiles() []profile.ScaffoldFile {
	files := make([]profile.ScaffoldFile, len(wantBasePaths))
	for i, p := range wantBasePaths {
		files[i] = profile.ScaffoldFile{Path: p}
	}
	return files
}

// sectionOpen casa a abertura de uma seção XML do CLAUDE.md, ex "<workflow>".
var sectionOpen = regexp.MustCompile(`^<([a-z_]+)>$`)

func TestWriteFilesCreatesBaseSetAndSystemFiles(t *testing.T) {
	target := t.TempDir()
	files := append(baseFiles(), SystemFiles()...)

	res, err := WriteFiles(files, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	})
	if err != nil {
		t.Fatalf("WriteFiles() error = %v", err)
	}
	if len(res.Skipped) != 0 {
		t.Fatalf("Skipped = %v, want none on first write", res.Skipped)
	}
	if len(res.Created) != len(files) {
		t.Fatalf("Created = %v, want %d entries", res.Created, len(files))
	}

	for _, p := range wantBasePaths {
		if _, err := os.Stat(filepath.Join(target, p)); err != nil {
			t.Fatalf("stat %s: %v", p, err)
		}
	}

	claude, err := os.ReadFile(filepath.Join(target, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(claude), "demo") {
		t.Fatalf("CLAUDE.md = %q, want it to mention the project name", claude)
	}

	info, err := os.Stat(filepath.Join(target, ".claude/hooks/session-start.sh"))
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o755 {
		t.Fatalf("session-start.sh mode = %v, want 0755", info.Mode().Perm())
	}
}

func TestWriteFilesNoOverwriteUnlessForce(t *testing.T) {
	target := t.TempDir()
	files := []profile.ScaffoldFile{{Path: "CLAUDE.md"}}
	opts := Options{Target: target, Data: Data{ProjectName: "demo", Stack: "go"}}

	if _, err := WriteFiles(files, opts); err != nil {
		t.Fatal(err)
	}

	custom := []byte("minha edição")
	path := filepath.Join(target, "CLAUDE.md")
	if err := os.WriteFile(path, custom, 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := WriteFiles(files, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Skipped) != 1 || res.Skipped[0] != "CLAUDE.md" {
		t.Fatalf("Skipped = %v, want [CLAUDE.md]", res.Skipped)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(custom) {
		t.Fatalf("content overwritten: got %q, want %q", got, custom)
	}

	opts.Force = true
	res, err = WriteFiles(files, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Created) != 1 || res.Created[0] != "CLAUDE.md" {
		t.Fatalf("Created = %v, want [CLAUDE.md] with --force", res.Created)
	}
	got, err = os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) == string(custom) {
		t.Fatal("--force did not regenerate the file")
	}
}

func TestWriteFilesHandoffImmuneToForce(t *testing.T) {
	target := t.TempDir()
	files := []profile.ScaffoldFile{{Path: ".claude/handoff.md"}}
	opts := Options{Target: target, Data: Data{ProjectName: "demo", Stack: "go"}}

	if _, err := WriteFiles(files, opts); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(target, ".claude/handoff.md")
	custom := []byte("estado da sessão anterior")
	if err := os.WriteFile(path, custom, 0o644); err != nil {
		t.Fatal(err)
	}

	opts.Force = true
	res, err := WriteFiles(files, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Created) != 0 {
		t.Fatalf("Created = %v, want none: handoff.md must never be regenerated by --force", res.Created)
	}
	if len(res.Skipped) != 1 || res.Skipped[0] != ".claude/handoff.md" {
		t.Fatalf("Skipped = %v, want [.claude/handoff.md]", res.Skipped)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(custom) {
		t.Fatalf("handoff.md overwritten despite --force: got %q, want %q", got, custom)
	}
}

func TestWriteFilesDryRunDoesNotWrite(t *testing.T) {
	target := t.TempDir()
	var out bytes.Buffer
	files := []profile.ScaffoldFile{{Path: "CLAUDE.md"}}

	res, err := WriteFiles(files, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
		DryRun: true,
		Out:    &out,
	})
	if err != nil {
		t.Fatalf("WriteFiles() error = %v", err)
	}
	if _, err := os.Stat(filepath.Join(target, "CLAUDE.md")); !os.IsNotExist(err) {
		t.Fatalf("CLAUDE.md should not exist after dry-run, stat err = %v", err)
	}
	if !strings.Contains(out.String(), "CLAUDE.md") {
		t.Fatalf("dry-run output = %q, want it to mention CLAUDE.md", out.String())
	}
	if len(res.Created) != 1 {
		t.Fatalf("Created = %v, want dry-run to still report what would be created", res.Created)
	}
}

func TestWriteFilesUnknownPathErrors(t *testing.T) {
	target := t.TempDir()
	files := []profile.ScaffoldFile{{Path: "nope.txt"}}

	if _, err := WriteFiles(files, Options{Target: target}); err == nil {
		t.Fatal("WriteFiles() = nil error, want error for unmapped path")
	}
}

func TestEnsureTemplatesOverlayWinsOverEmbed(t *testing.T) {
	overlayDir := t.TempDir()
	if _, err := EnsureTemplates(overlayDir, EnsureOptions{}); err != nil {
		t.Fatalf("EnsureTemplates() error = %v", err)
	}

	overlayFile := filepath.Join(overlayDir, "CLAUDE.md.tmpl")
	if _, err := os.Stat(overlayFile); err != nil {
		t.Fatalf("stat overlay CLAUDE.md.tmpl: %v", err)
	}
	custom := []byte("# {{.ProjectName}} (overlay custom)")
	if err := os.WriteFile(overlayFile, custom, 0o644); err != nil {
		t.Fatal(err)
	}

	target := t.TempDir()
	_, err := WriteFiles([]profile.ScaffoldFile{{Path: "CLAUDE.md"}}, Options{
		Target:       target,
		Data:         Data{ProjectName: "demo"},
		TemplatesDir: overlayDir,
	})
	if err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(target, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "overlay custom") {
		t.Fatalf("CLAUDE.md = %q, want overlay content to win", got)
	}
}

func TestMergeGitignoreCreatesWhitelistAndBlacklist(t *testing.T) {
	target := t.TempDir()

	if err := MergeGitignore(target, nil, Data{}, false, nil); err != nil {
		t.Fatalf("MergeGitignore() error = %v", err)
	}

	got, err := os.ReadFile(filepath.Join(target, ".gitignore"))
	if err != nil {
		t.Fatalf("stat .gitignore: %v", err)
	}
	content := string(got)

	for _, want := range []string{
		"!.claude/skills/", "!.claude/agents/", "!.claude/commands/",
		"!.claude/settings.json", "!.mcp.json", "!docs/",
		"!.claude/.ray-profile", "!**/.ray-origin", "!**/LICENSE",
	} {
		if !strings.Contains(content, want) {
			t.Errorf(".gitignore missing whitelist entry %q\n---\n%s", want, content)
		}
	}
	for _, want := range []string{
		"graphify-out/", ".claude/.ray-metrics/", ".claude/.local/", ".claude/handoff.md", ".env", "*.local",
	} {
		if !strings.Contains(content, want) {
			t.Errorf(".gitignore missing blacklist entry %q\n---\n%s", want, content)
		}
	}
}

func TestMergeGitignoreStackBlock(t *testing.T) {
	target := t.TempDir()

	if err := MergeGitignore(target, []string{"# Go", "/{{.ProjectName}}"}, Data{ProjectName: "demo"}, false, nil); err != nil {
		t.Fatalf("MergeGitignore() error = %v", err)
	}

	got, err := os.ReadFile(filepath.Join(target, ".gitignore"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "/demo") {
		t.Fatalf(".gitignore = %q, want the stack block rendered with the project name", got)
	}
	if strings.Contains(string(got), "{{.ProjectName}}") {
		t.Fatalf(".gitignore = %q, want the stack block template resolved, not raw", got)
	}
}

func TestMergeGitignoreIdempotent(t *testing.T) {
	target := t.TempDir()

	for i := 0; i < 2; i++ {
		if err := MergeGitignore(target, []string{"/bin/"}, Data{}, false, nil); err != nil {
			t.Fatalf("MergeGitignore() run %d error = %v", i, err)
		}
	}

	got, err := os.ReadFile(filepath.Join(target, ".gitignore"))
	if err != nil {
		t.Fatal(err)
	}
	if n := strings.Count(string(got), "# >>> ray"); n != 1 {
		t.Fatalf("marker count = %d, want exactly 1 (no duplicate block): %q", n, got)
	}
}

func TestMergeGitignorePreservesExistingLines(t *testing.T) {
	target := t.TempDir()
	path := filepath.Join(target, ".gitignore")
	if err := os.WriteFile(path, []byte("node_modules/\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := MergeGitignore(target, nil, Data{}, false, nil); err != nil {
		t.Fatalf("MergeGitignore() error = %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "node_modules/") {
		t.Fatalf(".gitignore lost pre-existing line: %q", got)
	}
	if !strings.Contains(string(got), "graphify-out/") {
		t.Fatalf(".gitignore missing ray block after merge: %q", got)
	}
}

func TestMergeGitignoreDryRunDoesNotWrite(t *testing.T) {
	target := t.TempDir()
	var out bytes.Buffer

	if err := MergeGitignore(target, nil, Data{}, true, &out); err != nil {
		t.Fatalf("MergeGitignore() error = %v", err)
	}
	if _, err := os.Stat(filepath.Join(target, ".gitignore")); !os.IsNotExist(err) {
		t.Fatalf(".gitignore should not exist after dry-run, stat err = %v", err)
	}
	if !strings.Contains(out.String(), "graphify-out/") {
		t.Fatalf("dry-run output = %q, want it to show the block", out.String())
	}
}

func TestEnsureTemplatesKeepsLocallyEditedFile(t *testing.T) {
	overlayDir := t.TempDir()
	overlayFile := filepath.Join(overlayDir, "CLAUDE.md.tmpl")
	if err := os.MkdirAll(overlayDir, 0o755); err != nil {
		t.Fatal(err)
	}
	custom := []byte("pré-existente")
	if err := os.WriteFile(overlayFile, custom, 0o644); err != nil {
		t.Fatal(err)
	}

	synced, err := EnsureTemplates(overlayDir, EnsureOptions{})
	if err != nil {
		t.Fatalf("EnsureTemplates() error = %v", err)
	}

	got, err := os.ReadFile(overlayFile)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(custom) {
		t.Fatalf("EnsureTemplates overwrote an edited file: got %q, want %q", got, custom)
	}
	if act := actionFor(synced, "CLAUDE.md.tmpl"); act.Action != TemplateKept {
		t.Fatalf("action = %q, want %q", act.Action, TemplateKept)
	} else if act.Reason == "" {
		t.Error("Kept without a Reason: the user is not told why the file did not update")
	}
}

func actionFor(synced []TemplateSync, rel string) TemplateSync {
	for _, s := range synced {
		if s.Rel == rel {
			return s
		}
	}
	return TemplateSync{}
}

// A regressão que motivou a mudança: overlay gerado por uma versão antiga do
// ray continuava ganhando do embed depois de o binário atualizar, porque
// EnsureTemplates só criava o que faltava. Como o `render` prefere o overlay,
// atualizar o ray deixava de atualizar os templates — em silêncio.
func TestEnsureTemplatesRefreshesUntouchedStaleFile(t *testing.T) {
	overlayDir := t.TempDir()
	rel := "CLAUDE.md.tmpl"
	overlayFile := filepath.Join(overlayDir, rel)

	stale := []byte("conteúdo de uma versão antiga do ray")
	if err := os.WriteFile(overlayFile, stale, 0o644); err != nil {
		t.Fatal(err)
	}
	// Linha-base: o ray gravou este hash quando escreveu o arquivo, então
	// ninguém o editou desde então.
	pristine := map[string]string{rel: store.HashBytes(stale)}

	synced, err := EnsureTemplates(overlayDir, EnsureOptions{
		Pristine: func(r string) (string, bool) { h, ok := pristine[r]; return h, ok },
	})
	if err != nil {
		t.Fatalf("EnsureTemplates() error = %v", err)
	}

	got, err := os.ReadFile(overlayFile)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) == string(stale) {
		t.Fatal("untouched stale overlay was not refreshed: the embed is still shadowed")
	}
	fresh, err := embedded.ReadFile(templatesRoot + "/" + rel)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(fresh) {
		t.Error("refreshed overlay does not match the embed")
	}

	act := actionFor(synced, rel)
	if act.Action != TemplateRefreshed {
		t.Fatalf("action = %q, want %q", act.Action, TemplateRefreshed)
	}
	if act.Hash != store.HashBytes(fresh) {
		t.Error("returned Hash is not that of the written content: the new baseline would be wrong")
	}
}

// --force atropela mesmo edição local, igual ao `ray update`.
func TestEnsureTemplatesForceOverwritesEditedFile(t *testing.T) {
	overlayDir := t.TempDir()
	rel := "CLAUDE.md.tmpl"
	overlayFile := filepath.Join(overlayDir, rel)
	if err := os.WriteFile(overlayFile, []byte("editado à mão"), 0o644); err != nil {
		t.Fatal(err)
	}

	if _, err := EnsureTemplates(overlayDir, EnsureOptions{Force: true}); err != nil {
		t.Fatalf("EnsureTemplates() error = %v", err)
	}

	got, err := os.ReadFile(overlayFile)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) == "editado à mão" {
		t.Error("--force did not overwrite the edited overlay")
	}
}

// Caso mais comum de todos: overlay já igual ao embed. Não é "editado" nem
// precisa de escrita, e não deve gerar aviso.
func TestEnsureTemplatesCurrentFileIsSilent(t *testing.T) {
	overlayDir := t.TempDir()
	if _, err := EnsureTemplates(overlayDir, EnsureOptions{}); err != nil {
		t.Fatal(err)
	}
	synced, err := EnsureTemplates(overlayDir, EnsureOptions{})
	if err != nil {
		t.Fatal(err)
	}
	for _, s := range synced {
		if s.Action != TemplateCurrent {
			t.Errorf("%s: action = %q na segunda passada, want %q", s.Rel, s.Action, TemplateCurrent)
		}
	}
}

// A ordem das seções do CLAUDE.md é load-bearing, não estética: <workflow> fica
// perto do fim de propósito, porque instrução de processo no topo é atropelada
// pelo volume da spec colada no turno. E <edge_cases> é a cláusula que impede
// invenção quando a premissa falha — ela fecha o documento.
func TestClaudeMdKeepsSectionOrder(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{{Path: "CLAUDE.md"}}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	body, err := os.ReadFile(filepath.Join(target, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}

	want := []string{
		"role", "context", "stack", "documentation_sources",
		"architecture", "test_strategy", "conventions", "quality_gates",
		"workflow", "agent_behavior", "output_format", "edge_cases",
	}

	var got []string
	for _, line := range strings.Split(string(body), "\n") {
		m := sectionOpen.FindStringSubmatch(line)
		if m != nil {
			got = append(got, m[1])
		}
	}
	if !slices.Equal(got, want) {
		t.Fatalf("sections = %v, want %v", got, want)
	}

	// Toda seção aberta precisa fechar, ou o bloco vira lixo no prompt.
	for _, s := range want {
		if !strings.Contains(string(body), "</"+s+">") {
			t.Errorf("section <%s> is not closed", s)
		}
	}
}

func TestDestilarCommandCarriesLoadBearingRules(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{{Path: ".claude/commands/destilar.md"}}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	body, err := os.ReadFile(filepath.Join(target, ".claude", "commands", "destilar.md"))
	if err != nil {
		t.Fatal(err)
	}
	txt := string(body)

	// Cada string abaixo é uma regra que, se sumir, muda o que o comando faz.
	// O portão de status impede destilar plano; a regra de evidência é o que
	// impede docs/ de nascer mentindo; "espere OK" protege a decisão travada;
	// "não invente trabalho" impede relatório inflado quando não há nada.
	for _, s := range []string{
		"não se destila plano",
		"implementada",
		"não vira texto",
		"espere OK",
		"Não invente trabalho",
	} {
		if !strings.Contains(txt, s) {
			t.Errorf("destilar.md perdeu a regra %q", s)
		}
	}

	// A tabela seção→destino é o coração do comando: sem ela, /destilar não
	// sabe para onde cada seção da spec vai.
	for _, s := range []string{
		"| Seção da spec | Destino |",
		"Regras de negócio e invariantes",
		"Contratos",
		"docs/architecture.md",
		"docs/conventions.md",
	} {
		if !strings.Contains(txt, s) {
			t.Errorf("destilar.md lost the section-to-destination table: missing %q", s)
		}
	}
}

func TestDocsReadmeLoopEndsInDistillation(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{{Path: "docs/README.md"}}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	body, err := os.ReadFile(filepath.Join(target, "docs", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	txt := string(body)

	if !strings.Contains(txt, "/destilar") {
		t.Error("the loop must end at /destilar")
	}
	// A spec fica no cérebro. Se o README voltar a mandar publicá-la em
	// docs/specs/, o laço contradiz a regra de roteamento.
	if strings.Contains(txt, "docs/specs/") {
		t.Error("docs/README.md must not tell anyone to publish specs under docs/specs/")
	}
}

func TestSpecTemplateIsNotScaffolded(t *testing.T) {
	// A spec vive no cérebro; o template dela também. Scaffoldar um
	// TEMPLATE.md no repo cria uma segunda fonte que diverge da primeira.
	if _, ok := templateFor["docs/specs/TEMPLATE.md"]; ok {
		t.Error("docs/specs/TEMPLATE.md must no longer be scaffolded")
	}
}

func TestWorkflowStep8DelegatesToDestilar(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{{Path: "CLAUDE.md"}}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	body, err := os.ReadFile(filepath.Join(target, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	txt := string(body)

	if !strings.Contains(txt, "/destilar") {
		t.Error("o passo de fechamento da spec precisa delegar ao /destilar")
	}
	// Orçamento do cabeçalho: o arquivo entra em contexto em todo turno.
	if n := strings.Count(txt, "\n"); n > 300 {
		t.Errorf("CLAUDE.md = %d lines, budget is 300", n)
	}
}

func TestHandoffAndRevisarDoNotReadDocsSpecs(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{
		{Path: ".claude/commands/handoff.md"},
		{Path: ".claude/commands/revisar.md"},
	}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	// A spec fica no cérebro, nunca em docs/specs/ do repo. Se qualquer um dos
	// dois comandos voltar a citar esse path, ele nasce lendo um diretório que
	// o scaffold não cria — quebrado em todo projeto novo.
	for _, p := range []string{".claude/commands/handoff.md", ".claude/commands/revisar.md"} {
		body, err := os.ReadFile(filepath.Join(target, filepath.FromSlash(p)))
		if err != nil {
			t.Fatal(err)
		}
		if strings.Contains(string(body), "docs/specs/") {
			t.Errorf("%s must not read the spec from docs/specs/", p)
		}
	}
}

func TestBrainCommandsGuardMissingBrain(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{
		{Path: ".claude/commands/destilar.md"},
		{Path: ".claude/commands/revisar.md"},
	}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	// Os dois comandos leem a spec direto do cérebro, por filesystem. Num
	// projeto sem cérebro configurado, sem esta guarda eles falham no meio da
	// leitura, sem dizer o que fazer. A guarda é a única saída acionável que o
	// usuário tem.
	for _, p := range []string{".claude/commands/destilar.md", ".claude/commands/revisar.md"} {
		body, err := os.ReadFile(filepath.Join(target, filepath.FromSlash(p)))
		if err != nil {
			t.Fatal(err)
		}
		txt := string(body)
		for _, want := range []string{
			"não estiver configurado",
			"ray brain set",
		} {
			if !strings.Contains(txt, want) {
				t.Errorf("%s perdeu a guarda de brain ausente: falta %q", p, want)
			}
		}
	}
}

func TestGitignoreIgnoresHandoff(t *testing.T) {
	target := t.TempDir()

	if err := MergeGitignore(target, nil, Data{}, false, nil); err != nil {
		t.Fatalf("MergeGitignore() error = %v", err)
	}

	body, err := os.ReadFile(filepath.Join(target, ".gitignore"))
	if err != nil {
		t.Fatal(err)
	}
	got := string(body)

	// O handoff descreve onde o trabalho parou — processo, não estado do
	// sistema. Ele é regenerado inteiro a cada /handoff e é gerido pela IA.
	// Sem uma linha explícita ele fica untracked para sempre e cada projeto
	// decide por acidente.
	if !strings.Contains(got, ".claude/handoff.md") {
		t.Errorf(".gitignore block does not mention .claude/handoff.md:\n%s", got)
	}
	// Precisa estar na blacklist, não negado no whitelist.
	if strings.Contains(got, "!.claude/handoff.md") {
		t.Error("got = handoff no whitelist, want na blacklist")
	}
}

func TestRevisarAsksForCrossFamilyReview(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{{Path: ".claude/commands/revisar.md"}}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	body, err := os.ReadFile(filepath.Join(target, ".claude", "commands", "revisar.md"))
	if err != nil {
		t.Fatal(err)
	}
	txt := string(body)

	// A política de assentos pede revisor de outra família de modelo: autor e
	// revisor da mesma família compartilham ponto cego. O comando que executa a
	// revisão precisa dizer isso, senão a regra fica só no CLAUDE.md e nunca
	// vira ação.
	for _, want := range []string{
		"outra família",
		"ponto cego",
	} {
		if !strings.Contains(txt, want) {
			t.Errorf("revisar.md does not ask for a reviewer from another model family: missing %q", want)
		}
	}
}

// hasJQ reporta se jq existe no ambiente. Os hooks fazem no-op sem ele, então
// o teste de comportamento não tem o que afirmar.
func hasJQ(t *testing.T) bool {
	t.Helper()
	res, err := runner.ExecRunner{}.Run(context.Background(), runner.Command{
		Name: "bash", Args: []string{"-c", "command -v jq >/dev/null 2>&1"},
	})
	return err == nil && res.ExitCode == 0
}

// runHook renderiza um hook num diretório temporário, alimenta-o com payload
// pela stdin e devolve o resultado. Usa runner.ExecRunner de propósito: é a
// fronteira do projeto para processo externo, e evita uma terceira importação
// de os/exec.
func runHook(t *testing.T, script, payload string) runner.Result {
	t.Helper()
	dir := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{{Path: ".claude/hooks/" + script}}, Options{
		Target: dir,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	payloadPath := filepath.Join(dir, "payload.json")
	if err := os.WriteFile(payloadPath, []byte(payload), 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := runner.ExecRunner{}.Run(context.Background(), runner.Command{
		Name: "bash",
		Args: []string{"-c", "cat " + payloadPath + " | bash " + filepath.Join(dir, ".claude/hooks/"+script)},
		Dir:  dir,
	})
	if err != nil {
		t.Fatalf("rodando %s: %v", script, err)
	}
	return res
}

func TestGuardAddWarnsOnBlindAdd(t *testing.T) {
	if !hasJQ(t) {
		t.Skip("jq ausente; o hook faz no-op por design")
	}

	cases := []struct {
		name    string
		command string
		warns   bool
	}{
		{"add -A", "git add -A", true},
		{"add --all", "git add --all", true},
		{"add ponto", "git add .", true},
		{"add seletivo", "git add internal/scaffold/scaffold.go", false},
		{"commit qualquer", "git commit -m 'x'", false},
		{"add dentro de outra palavra", "echo 'git added'", false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			payload := `{"tool_input":{"command":` + strconv.Quote(tc.command) + `}}`
			res := runHook(t, "guard-add.sh", payload)

			if res.ExitCode != 0 {
				t.Fatalf("ExitCode = %d, want 0: a warning hook never fails", res.ExitCode)
			}
			warned := strings.Contains(res.Stdout, "systemMessage")
			if warned != tc.warns {
				t.Errorf("avisou = %v, want %v (stdout: %q)", warned, tc.warns, res.Stdout)
			}
		})
	}
}

func TestGuardVocabWarnsOnDeliveredArtifacts(t *testing.T) {
	if !hasJQ(t) {
		t.Skip("jq ausente; o hook faz no-op por design")
	}

	cases := []struct {
		name    string
		relPath string
		content string
		warns   bool
	}{
		{"readme cita spec numerada", "README.md", "Ver spec 012 para detalhes.\n", true},
		{"codigo cita CA", "internal/foo/foo.go", "// implementa CA-03\n", true},
		{"codigo cita RF", "internal/foo/foo.go", "// conforme RF-07\n", true},
		{"readme cita criterio de aceite", "README.md", "Cada critério de aceite vira teste.\n", true},
		{"teste pode citar CA", "internal/foo/foo_test.go", "// CA-01: rejeita vazio\n", false},
		{"CLAUDE.md pode citar spec", "CLAUDE.md", "Ao receber uma spec 012, siga.\n", false},
		{"claude dir pode citar", ".claude/commands/x.md", "Leia a spec 012.\n", false},
		{"OpenAPI spec passa limpo", "README.md", "Servimos uma OpenAPI spec em /docs.\n", false},
		{"spec-driven passa limpo", "README.md", "Fluxo spec-driven development.\n", false},
		// A isenção de teste vale por segmento inteiro, não por substring:
		// "latest" e "attestation" contêm "test" e são artefato entregue.
		{"latest nao e diretorio de teste", "docs/latest/README.md", "Ver spec 012.\n", true},
		{"attestation nao e diretorio de teste", "attestation/README.md", "Ver spec 012.\n", true},
		{"diretorio test de verdade e isento", "test/helper.md", "Ver spec 012.\n", false},
		{"diretorio tests de verdade e isento", "pkg/tests/helper.md", "Ver spec 012.\n", false},
		// .superpowers/ é diretório de sessão local, não artefato entregue.
		// Acusá-lo faz o hook gritar justamente onde a nota de processo mora,
		// e ruído é o que faz um hook de aviso deixar de ser lido.
		{"superpowers e sessao local", ".superpowers/sdd/progress.md", "Task 1 fecha o CA-01 da spec 012.\n", false},
		{"superpowers aninhado", "sub/.superpowers/x.md", "Ver spec 012.\n", false},
		// Simétrico aos casos de "latest"/"attestation" acima: a isenção vale
		// pelo segmento `.superpowers` inteiro, com o ponto. Sem estes dois, um
		// padrão frouxo (`*superpowers*`) passa na suíte e cala o hook justamente
		// em docs/superpowers/, que é artefato entregue — não sessão local.
		{"docs superpowers e artefato entregue", "docs/superpowers/plans/x.md", "Ver spec 012.\n", true},
		{"superpowers sem ponto nao e isento", "superpowers/x.md", "Ver spec 012.\n", true},
		// Um guard precisa escrever o vocabulário que caça. Sem a isenção ele
		// se acusa a cada edição — e o template, que é de onde a cópia sai, não
		// mora sob `.claude/`, então não pegava carona na isenção de lá. A
		// cópia gerada não precisa de caso próprio: `.claude/*` já a isenta.
		{"o template do guard e isento", "internal/scaffold/templates/claude/hooks/guard-vocab.sh.tmpl", "grep -E 'CA-[0-9]|critério de aceite'\n", false},
		// A isenção é do guard, não de qualquer arquivo sob hooks/: doc de hook
		// é artefato entregue como outro qualquer.
		{"doc de hooks nao e isento", "docs/hooks/README.md", "Ver spec 012.\n", true},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			target := filepath.Join(dir, filepath.FromSlash(tc.relPath))

			// O arquivo não é escrito no disco de propósito: o hook não o lê
			// mais, e um teste que o escrevesse não distinguiria as duas fontes.
			payload := `{"tool_input":{"file_path":` + strconv.Quote(target) +
				`,"new_string":` + strconv.Quote(tc.content) + `}}`

			res := runGuardVocab(t, dir, payload)
			warned := strings.Contains(res.Stdout, "systemMessage")
			if warned != tc.warns {
				t.Errorf("avisou = %v, want %v (stdout: %q)", warned, tc.warns, res.Stdout)
			}
			if warned && !strings.Contains(res.Stdout, tc.relPath) {
				t.Errorf("stdout does not name the file: %q", res.Stdout)
			}
		})
	}
}

// runGuardVocab escreve o hook num diretório temporário, entrega o payload por
// stdin e devolve o resultado. O hook roda com cwd na raiz do diretório, que é
// de onde o Claude Code o invoca.
//
// O contrato de saída é dos irmãos: aviso por systemMessage e exit 0, nunca
// exit 2 — que devolveria o achado como erro e interromperia o turno. Por isso
// o exit code é conferido aqui, uma vez, e não em cada caso.
func runGuardVocab(t *testing.T, dir, payload string) runner.Result {
	t.Helper()

	if _, err := WriteFiles([]profile.ScaffoldFile{{Path: ".claude/hooks/guard-vocab.sh"}}, Options{
		Target: dir,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	payloadPath := filepath.Join(dir, "payload.json")
	if err := os.WriteFile(payloadPath, []byte(payload), 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := runner.ExecRunner{}.Run(context.Background(), runner.Command{
		Name: "bash",
		Args: []string{"-c", "cat " + payloadPath + " | bash " + filepath.Join(dir, ".claude/hooks/guard-vocab.sh")},
		Dir:  dir,
	})
	if err != nil {
		t.Fatalf("rodando guard-vocab.sh: %v", err)
	}
	if res.ExitCode != 0 {
		t.Fatalf("ExitCode = %d, want 0: a warning hook never fails", res.ExitCode)
	}
	return res
}

// O hook não lê o disco. Um arquivo cheio de vocabulário antigo, editado por uma
// chamada que não acrescenta nenhum, não rende aviso — era esse aviso, sobre
// linha que o autor da edição não escreveu, que se repetia a cada edição.
func TestGuardVocabIgnoresWhatTheEditDidNotWrite(t *testing.T) {
	if !hasJQ(t) {
		t.Skip("jq ausente; o hook faz no-op por design")
	}

	dir := t.TempDir()
	target := filepath.Join(dir, "README.md")
	if err := os.WriteFile(target, []byte("Ver spec 012 para detalhes.\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	payload := `{"tool_input":{"file_path":` + strconv.Quote(target) +
		`,"new_string":"Uma frase inteiramente limpa.\n"}}`

	res := runGuardVocab(t, dir, payload)
	if strings.Contains(res.Stdout, "systemMessage") {
		t.Errorf("warned about text the edit did not write: %q", res.Stdout)
	}
}

// Os três campos que carregam texto escrito, um por ferramenta. O arquivo não
// existe no disco em nenhum dos casos: se o hook ainda dependesse dele, os três
// passariam em silêncio.
func TestGuardVocabReadsEveryWrittenTextField(t *testing.T) {
	if !hasJQ(t) {
		t.Skip("jq ausente; o hook faz no-op por design")
	}

	cases := []struct {
		name  string
		input string
	}{
		{"content do Write", `"content":"Ver spec 012.\n"`},
		{"new_string do Edit", `"new_string":"Ver spec 012.\n"`},
		{"edits do MultiEdit", `"edits":[{"new_string":"linha limpa\n"},{"new_string":"Ver spec 012.\n"}]`},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			target := filepath.Join(dir, "README.md")

			payload := `{"tool_input":{"file_path":` + strconv.Quote(target) + `,` + tc.input + `}}`

			res := runGuardVocab(t, dir, payload)
			if !strings.Contains(res.Stdout, "systemMessage") {
				t.Errorf("did not warn: %q", res.Stdout)
			}
			if !strings.Contains(res.Stdout, "README.md") {
				t.Errorf("stdout does not name the file: %q", res.Stdout)
			}
		})
	}
}

// Payload sem nenhum dos três campos — uma chamada que só apaga, por exemplo.
// Nada a varrer é silêncio, não erro.
func TestGuardVocabIsSilentWithoutWrittenText(t *testing.T) {
	if !hasJQ(t) {
		t.Skip("jq ausente; o hook faz no-op por design")
	}

	dir := t.TempDir()
	target := filepath.Join(dir, "README.md")

	res := runGuardVocab(t, dir, `{"tool_input":{"file_path":`+strconv.Quote(target)+`}}`)
	if strings.TrimSpace(res.Stdout) != "" {
		t.Errorf("stdout = %q, want empty with nothing written", res.Stdout)
	}
}

func TestGuardPlansWarnsOnRepoPlans(t *testing.T) {
	if !hasJQ(t) {
		t.Skip("jq ausente; o hook faz no-op por design")
	}

	cases := []struct {
		name  string
		path  string
		warns bool
	}{
		{"plano em docs/superpowers", "/repo/docs/superpowers/plans/x.md", true},
		{"design em docs/superpowers", "/repo/docs/superpowers/specs/x-design.md", true},
		{"superpowers na raiz", "/repo/superpowers/plano.md", true},
		{"doc normal", "/repo/docs/architecture.md", false},
		{"codigo", "/repo/internal/foo/foo.go", false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			payload := `{"tool_input":{"file_path":` + strconv.Quote(tc.path) + `}}`
			res := runHook(t, "guard-plans.sh", payload)

			if res.ExitCode != 0 {
				t.Fatalf("ExitCode = %d, want 0: a warning hook never fails", res.ExitCode)
			}
			warned := strings.Contains(res.Stdout, "systemMessage")
			if warned != tc.warns {
				t.Errorf("avisou = %v, want %v (stdout: %q)", warned, tc.warns, res.Stdout)
			}
		})
	}
}

func TestClaudeMdNamesPlanDestination(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{{Path: "CLAUDE.md"}}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	body, err := os.ReadFile(filepath.Join(target, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	txt := string(body)

	// A skill escreve onde a instrução mandar. Sem o destino nomeado aqui, ela
	// usa o default dela — docs/superpowers/ — e o hook só avisa depois.
	if !strings.Contains(txt, "plano e design") {
		t.Error("CLAUDE.md does not say where plans and designs live")
	}
	if !strings.Contains(txt, "superpowers") {
		t.Error("CLAUDE.md does not name the directory that must not be used")
	}
	if n := strings.Count(txt, "\n"); n > 300 {
		t.Errorf("CLAUDE.md = %d lines, budget is 300", n)
	}
}

func TestFileEditingHooksCoverMultiEdit(t *testing.T) {
	// Um hook que inspeciona arquivo e esquece MultiEdit tem buraco
	// silencioso: a edição em lote é caminho comum e passaria sem aviso.
	hooks := HookSettings()["hooks"].(map[string]any)
	for _, event := range []string{"PreToolUse", "PostToolUse"} {
		entries, ok := hooks[event].([]any)
		if !ok {
			continue
		}
		for _, e := range entries {
			matcher, _ := e.(map[string]any)["matcher"].(string)
			if matcher == "Bash" {
				continue // guard-add lê comando, não arquivo
			}
			if !strings.Contains(matcher, "MultiEdit") {
				t.Errorf("%s matcher = %q, want cobrindo MultiEdit", event, matcher)
			}
		}
	}
}

// TestREADMEExplainsVendoring guarda a resposta à pergunta que o rodapé de
// próximos passos provoca: por que commitar o que o `ray init ai` acabou de
// escrever. Sem ela, o I1 termina com uma instrução sem justificativa.
func TestREADMEExplainsVendoring(t *testing.T) {
	root := repoRoot(t)
	data, err := os.ReadFile(filepath.Join(root, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	txt := string(data)
	for _, want := range []string{
		"O ambiente de IA é versionado",
		".claude/.local/",
		".mcp.json",
	} {
		if !strings.Contains(txt, want) {
			t.Errorf("README.md does not mention %q", want)
		}
	}
}

// TestGitignoreAccessorsMirrorTheBlock impede que os acessores públicos virem
// uma segunda fonte de verdade: eles devolvem o mesmo que o bloco escreve.
func TestGitignoreAccessorsMirrorTheBlock(t *testing.T) {
	begin, end := GitignoreMarkers()
	if begin != gitignoreMarkerBegin || end != gitignoreMarkerEnd {
		t.Errorf("GitignoreMarkers() = %q/%q, want %q/%q", begin, end, gitignoreMarkerBegin, gitignoreMarkerEnd)
	}
	if got := GitignoreBaseLines(); !slices.Equal(got, gitignoreBaseLines) {
		t.Errorf("GitignoreBaseLines() = %v, want %v", got, gitignoreBaseLines)
	}
	// Cópia, não alias: mutar o retorno não pode corromper o pacote.
	GitignoreBaseLines()[0] = "mutated"
	if gitignoreBaseLines[0] == "mutated" {
		t.Error("GitignoreBaseLines() returned an alias; a caller can corrupt the block")
	}
}
