package scaffold

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"

	"github.com/TheBud4/ray/internal/profile"
)

var wantBasePaths = []string{
	"CLAUDE.md",
	"SECURITY.md",
	"docs/README.md",
	"docs/architecture.md",
	"docs/conventions.md",
	".claude/commands/document.md",
	".claude/commands/handoff.md",
	".claude/commands/revisar.md",
	".claude/commands/destilar.md",
	".claude/handoff.md",
}

func baseFiles() []profile.ScaffoldFile {
	files := make([]profile.ScaffoldFile, len(wantBasePaths))
	for i, p := range wantBasePaths {
		files[i] = profile.ScaffoldFile{Path: p}
	}
	return files
}

// sectionOpen casa a abertura de uma seção XML do CLAUDE.md, ex "<workflow>".
var sectionOpen = regexp.MustCompile(`^<([a-z_]+)>$`)

func TestWriteFilesCreatesBaseSetAndSystemFiles(t *testing.T) {
	target := t.TempDir()
	files := append(baseFiles(), SystemFiles(ModeBuild)...)

	res, err := WriteFiles(files, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	})
	if err != nil {
		t.Fatalf("WriteFiles() error = %v", err)
	}
	if len(res.Skipped) != 0 {
		t.Fatalf("Skipped = %v, want none on first write", res.Skipped)
	}
	if len(res.Created) != len(files) {
		t.Fatalf("Created = %v, want %d entries", res.Created, len(files))
	}

	for _, p := range wantBasePaths {
		if _, err := os.Stat(filepath.Join(target, p)); err != nil {
			t.Fatalf("stat %s: %v", p, err)
		}
	}

	claude, err := os.ReadFile(filepath.Join(target, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(claude), "demo") {
		t.Fatalf("CLAUDE.md = %q, want it to mention the project name", claude)
	}

	info, err := os.Stat(filepath.Join(target, ".claude/hooks/session-start.sh"))
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o755 {
		t.Fatalf("session-start.sh mode = %v, want 0755", info.Mode().Perm())
	}
}

func TestWriteFilesNoOverwriteUnlessForce(t *testing.T) {
	target := t.TempDir()
	files := []profile.ScaffoldFile{{Path: "CLAUDE.md"}}
	opts := Options{Target: target, Data: Data{ProjectName: "demo", Stack: "go"}}

	if _, err := WriteFiles(files, opts); err != nil {
		t.Fatal(err)
	}

	custom := []byte("minha edição")
	path := filepath.Join(target, "CLAUDE.md")
	if err := os.WriteFile(path, custom, 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := WriteFiles(files, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Skipped) != 1 || res.Skipped[0] != "CLAUDE.md" {
		t.Fatalf("Skipped = %v, want [CLAUDE.md]", res.Skipped)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(custom) {
		t.Fatalf("content overwritten: got %q, want %q", got, custom)
	}

	opts.Force = true
	res, err = WriteFiles(files, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Created) != 1 || res.Created[0] != "CLAUDE.md" {
		t.Fatalf("Created = %v, want [CLAUDE.md] with --force", res.Created)
	}
	got, err = os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) == string(custom) {
		t.Fatal("--force did not regenerate the file")
	}
}

func TestWriteFilesHandoffImmuneToForce(t *testing.T) {
	target := t.TempDir()
	files := []profile.ScaffoldFile{{Path: ".claude/handoff.md"}}
	opts := Options{Target: target, Data: Data{ProjectName: "demo", Stack: "go"}}

	if _, err := WriteFiles(files, opts); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(target, ".claude/handoff.md")
	custom := []byte("estado da sessão anterior")
	if err := os.WriteFile(path, custom, 0o644); err != nil {
		t.Fatal(err)
	}

	opts.Force = true
	res, err := WriteFiles(files, opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Created) != 0 {
		t.Fatalf("Created = %v, want none: handoff.md must never be regenerated by --force", res.Created)
	}
	if len(res.Skipped) != 1 || res.Skipped[0] != ".claude/handoff.md" {
		t.Fatalf("Skipped = %v, want [.claude/handoff.md]", res.Skipped)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(custom) {
		t.Fatalf("handoff.md overwritten despite --force: got %q, want %q", got, custom)
	}
}

func TestWriteFilesDryRunDoesNotWrite(t *testing.T) {
	target := t.TempDir()
	var out bytes.Buffer
	files := []profile.ScaffoldFile{{Path: "CLAUDE.md"}}

	res, err := WriteFiles(files, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
		DryRun: true,
		Out:    &out,
	})
	if err != nil {
		t.Fatalf("WriteFiles() error = %v", err)
	}
	if _, err := os.Stat(filepath.Join(target, "CLAUDE.md")); !os.IsNotExist(err) {
		t.Fatalf("CLAUDE.md should not exist after dry-run, stat err = %v", err)
	}
	if !strings.Contains(out.String(), "CLAUDE.md") {
		t.Fatalf("dry-run output = %q, want it to mention CLAUDE.md", out.String())
	}
	if len(res.Created) != 1 {
		t.Fatalf("Created = %v, want dry-run to still report what would be created", res.Created)
	}
}

func TestWriteFilesUnknownPathErrors(t *testing.T) {
	target := t.TempDir()
	files := []profile.ScaffoldFile{{Path: "nope.txt"}}

	if _, err := WriteFiles(files, Options{Target: target}); err == nil {
		t.Fatal("WriteFiles() = nil error, want error for unmapped path")
	}
}

func TestEnsureTemplatesOverlayWinsOverEmbed(t *testing.T) {
	overlayDir := t.TempDir()
	if err := EnsureTemplates(overlayDir); err != nil {
		t.Fatalf("EnsureTemplates() error = %v", err)
	}

	overlayFile := filepath.Join(overlayDir, "CLAUDE.md.tmpl")
	if _, err := os.Stat(overlayFile); err != nil {
		t.Fatalf("stat overlay CLAUDE.md.tmpl: %v", err)
	}
	custom := []byte("# {{.ProjectName}} (overlay custom)")
	if err := os.WriteFile(overlayFile, custom, 0o644); err != nil {
		t.Fatal(err)
	}

	target := t.TempDir()
	_, err := WriteFiles([]profile.ScaffoldFile{{Path: "CLAUDE.md"}}, Options{
		Target:       target,
		Data:         Data{ProjectName: "demo"},
		TemplatesDir: overlayDir,
	})
	if err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(target, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "overlay custom") {
		t.Fatalf("CLAUDE.md = %q, want overlay content to win", got)
	}
}

func TestMergeGitignoreCreatesWhitelistAndBlacklist(t *testing.T) {
	target := t.TempDir()

	if err := MergeGitignore(target, nil, Data{}, false, nil); err != nil {
		t.Fatalf("MergeGitignore() error = %v", err)
	}

	got, err := os.ReadFile(filepath.Join(target, ".gitignore"))
	if err != nil {
		t.Fatalf("stat .gitignore: %v", err)
	}
	content := string(got)

	for _, want := range []string{
		"!.claude/skills/", "!.claude/agents/", "!.claude/commands/",
		"!.claude/settings.json", "!.mcp.json", "!docs/",
		"!.claude/.ray-profile", "!**/.ray-origin", "!**/LICENSE",
	} {
		if !strings.Contains(content, want) {
			t.Errorf(".gitignore missing whitelist entry %q\n---\n%s", want, content)
		}
	}
	for _, want := range []string{
		"graphify-out/", ".claude/.ray-metrics/", ".claude/.local/", ".env", "*.local",
	} {
		if !strings.Contains(content, want) {
			t.Errorf(".gitignore missing blacklist entry %q\n---\n%s", want, content)
		}
	}
}

func TestMergeGitignoreStackBlock(t *testing.T) {
	target := t.TempDir()

	if err := MergeGitignore(target, []string{"# Go", "/{{.ProjectName}}"}, Data{ProjectName: "demo"}, false, nil); err != nil {
		t.Fatalf("MergeGitignore() error = %v", err)
	}

	got, err := os.ReadFile(filepath.Join(target, ".gitignore"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "/demo") {
		t.Fatalf(".gitignore = %q, want the stack block rendered with the project name", got)
	}
	if strings.Contains(string(got), "{{.ProjectName}}") {
		t.Fatalf(".gitignore = %q, want the stack block template resolved, not raw", got)
	}
}

func TestMergeGitignoreIdempotent(t *testing.T) {
	target := t.TempDir()

	for i := 0; i < 2; i++ {
		if err := MergeGitignore(target, []string{"/bin/"}, Data{}, false, nil); err != nil {
			t.Fatalf("MergeGitignore() run %d error = %v", i, err)
		}
	}

	got, err := os.ReadFile(filepath.Join(target, ".gitignore"))
	if err != nil {
		t.Fatal(err)
	}
	if n := strings.Count(string(got), "# >>> ray"); n != 1 {
		t.Fatalf("marker count = %d, want exactly 1 (no duplicate block): %q", n, got)
	}
}

func TestMergeGitignorePreservesExistingLines(t *testing.T) {
	target := t.TempDir()
	path := filepath.Join(target, ".gitignore")
	if err := os.WriteFile(path, []byte("node_modules/\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := MergeGitignore(target, nil, Data{}, false, nil); err != nil {
		t.Fatalf("MergeGitignore() error = %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "node_modules/") {
		t.Fatalf(".gitignore lost pre-existing line: %q", got)
	}
	if !strings.Contains(string(got), "graphify-out/") {
		t.Fatalf(".gitignore missing ray block after merge: %q", got)
	}
}

func TestMergeGitignoreDryRunDoesNotWrite(t *testing.T) {
	target := t.TempDir()
	var out bytes.Buffer

	if err := MergeGitignore(target, nil, Data{}, true, &out); err != nil {
		t.Fatalf("MergeGitignore() error = %v", err)
	}
	if _, err := os.Stat(filepath.Join(target, ".gitignore")); !os.IsNotExist(err) {
		t.Fatalf(".gitignore should not exist after dry-run, stat err = %v", err)
	}
	if !strings.Contains(out.String(), "graphify-out/") {
		t.Fatalf("dry-run output = %q, want it to show the block", out.String())
	}
}

func TestEnsureTemplatesNeverOverwrites(t *testing.T) {
	overlayDir := t.TempDir()
	overlayFile := filepath.Join(overlayDir, "CLAUDE.md.tmpl")
	if err := os.MkdirAll(overlayDir, 0o755); err != nil {
		t.Fatal(err)
	}
	custom := []byte("pré-existente")
	if err := os.WriteFile(overlayFile, custom, 0o644); err != nil {
		t.Fatal(err)
	}

	if err := EnsureTemplates(overlayDir); err != nil {
		t.Fatalf("EnsureTemplates() error = %v", err)
	}

	got, err := os.ReadFile(overlayFile)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(custom) {
		t.Fatalf("EnsureTemplates overwrote a pre-existing overlay file: got %q, want %q", got, custom)
	}
}

// A ordem das seções do CLAUDE.md é load-bearing, não estética: <workflow> fica
// perto do fim de propósito, porque instrução de processo no topo é atropelada
// pelo volume da spec colada no turno. E <edge_cases> é a cláusula que impede
// invenção quando a premissa falha — ela fecha o documento.
func TestClaudeMdKeepsSectionOrder(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{{Path: "CLAUDE.md"}}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	body, err := os.ReadFile(filepath.Join(target, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}

	want := []string{
		"role", "context", "stack", "documentation_sources",
		"architecture", "test_strategy", "conventions", "quality_gates",
		"workflow", "agent_behavior", "output_format", "edge_cases",
	}

	var got []string
	for _, line := range strings.Split(string(body), "\n") {
		m := sectionOpen.FindStringSubmatch(line)
		if m != nil {
			got = append(got, m[1])
		}
	}
	if !slices.Equal(got, want) {
		t.Fatalf("seções = %v, want %v", got, want)
	}

	// Toda seção aberta precisa fechar, ou o bloco vira lixo no prompt.
	for _, s := range want {
		if !strings.Contains(string(body), "</"+s+">") {
			t.Errorf("seção <%s> não é fechada", s)
		}
	}
}

func TestDestilarCommandCarriesLoadBearingRules(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{{Path: ".claude/commands/destilar.md"}}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	body, err := os.ReadFile(filepath.Join(target, ".claude", "commands", "destilar.md"))
	if err != nil {
		t.Fatal(err)
	}
	txt := string(body)

	// Cada string abaixo é uma regra que, se sumir, muda o que o comando faz.
	// O portão de status impede destilar plano; a regra de evidência é o que
	// impede docs/ de nascer mentindo; "espere OK" protege a decisão travada;
	// "não invente trabalho" impede relatório inflado quando não há nada.
	for _, s := range []string{
		"status",
		"implementada",
		"não vira texto",
		"espere OK",
		"Não invente trabalho",
	} {
		if !strings.Contains(txt, s) {
			t.Errorf("destilar.md perdeu a regra %q", s)
		}
	}
}

func TestDocsReadmeLoopEndsInDistillation(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{{Path: "docs/README.md"}}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	body, err := os.ReadFile(filepath.Join(target, "docs", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	txt := string(body)

	if !strings.Contains(txt, "/destilar") {
		t.Error("o laço precisa terminar em /destilar")
	}
	// A spec fica no cérebro. Se o README voltar a mandar publicá-la em
	// docs/specs/, o laço contradiz a regra de roteamento.
	if strings.Contains(txt, "docs/specs/") {
		t.Error("docs/README.md não pode mandar publicar spec em docs/specs/")
	}
}

func TestSpecTemplateIsNotScaffolded(t *testing.T) {
	// A spec vive no cérebro; o template dela também. Scaffoldar um
	// TEMPLATE.md no repo cria uma segunda fonte que diverge da primeira.
	if _, ok := templateFor["docs/specs/TEMPLATE.md"]; ok {
		t.Error("docs/specs/TEMPLATE.md não deve mais ser scaffoldado")
	}
}

func TestWorkflowStep8DelegatesToDestilar(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{{Path: "CLAUDE.md"}}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	body, err := os.ReadFile(filepath.Join(target, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	txt := string(body)

	if !strings.Contains(txt, "/destilar") {
		t.Error("o passo de fechamento da spec precisa delegar ao /destilar")
	}
	// Orçamento do cabeçalho: o arquivo entra em contexto em todo turno.
	if n := strings.Count(txt, "\n"); n > 300 {
		t.Errorf("CLAUDE.md = %d linhas, orçamento é 300", n)
	}
}

func TestHandoffAndRevisarDoNotReadDocsSpecs(t *testing.T) {
	target := t.TempDir()

	if _, err := WriteFiles([]profile.ScaffoldFile{
		{Path: ".claude/commands/handoff.md"},
		{Path: ".claude/commands/revisar.md"},
	}, Options{
		Target: target,
		Data:   Data{ProjectName: "demo", Stack: "go"},
	}); err != nil {
		t.Fatal(err)
	}

	// A spec fica no cérebro, nunca em docs/specs/ do repo. Se qualquer um dos
	// dois comandos voltar a citar esse path, ele nasce lendo um diretório que
	// o scaffold não cria — quebrado em todo projeto novo.
	for _, p := range []string{".claude/commands/handoff.md", ".claude/commands/revisar.md"} {
		body, err := os.ReadFile(filepath.Join(target, filepath.FromSlash(p)))
		if err != nil {
			t.Fatal(err)
		}
		if strings.Contains(string(body), "docs/specs/") {
			t.Errorf("%s não pode ler a spec em docs/specs/", p)
		}
	}
}
